# Dopla admin mail
dopla_admin_mail: admin@example.com

# Volume directory
dopla_volume_path: /volumes

# Volumes to precreate
dopla_volumes:
  - vol01
  - vol02
  - vol03
  - vol04
  - vol05
  - vol06
  - vol07
  - vol08
  - vol09
  - vol10

# Dopla docker volume name
dopla_k8s_vol_name: k8spv
# Dopla docker volume size
dopla_k8s_vol_size: 50G
# Dopla host volume group
dopla_host_vg: system
# Use dopla to manage the volumes
dopla_manage_vols: true
# Dopla default fs for docker and k8s volumes
dopla_host_fstype: ext4