---
# Create a Bridge named dopla0 with the ip 10.10.10.10/24
# See: https://github.com/mrlesmithjr/ansible-netplan/blob/master/defaults/main.yml
- name: Build a list of all internal IPs that will run dnsmasq
  # This is a workaround because adding arrays does not work in 2.5.1:
  # dopla_int_dns: "{{ dopla_int_dns }} + [ '{{ hostvars[item].dopla_ip }}' ]"
  set_fact: dopla_dns_ip="{{ hostvars[item].dopla_ip }}"
  with_inventory_hostnames:
    - dopla-base
  register: dopla_dns_ips
- set_fact: dopla_int_dns="{{ dopla_dns_ips.results | map(attribute='ansible_facts.dopla_dns_ip') | list }}"

- name: Install docker, docker-python and all the dependencies.
  include_role:
    name: nickjj.docker
  vars:
    docker__state: "present"
    docker__registries: "{{dopla_registries}}"
    docker__default_daemon_json: |
      "log-driver": "json-file",
      "log-opts": {
        "max-size": "10m",
        "max-file": "10"
      }
