---
galaxy_info:
  author: Lukas Meyer
  description: Ansible role to configure and install docker ce on a host which has dopla-base installed.
  license: MIT
  min_ansible_version: 2.0
  platforms:
    - name: Ubuntu
      versions:
        - bionic
  categories:
    - datacenter
dependencies:
   - role: dopla-base
#     vars:
#       netplan_config_file: /etc/netplan/dopla.yaml
#       netplan_renderer: networkd
#       netplan_remove_existing: false
