apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: test-app-example-com
  namespace: demo-space
spec:
  secretName: test-app-example-com-tls
  issuerRef:
    # Change to letsencrypt 
    name: letsencrypt-issuer
    kind: ClusterIssuer
  commonName: test-app.example.com
  acme:
    config:
    - http01:
        ingressClass: nginx
      domains:
      - test-app.example.com